[2025-03-10T15:39:00.050+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T15:39:00.057+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T15:39:00.057+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T15:39:00.069+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-01 00:00:00+00:00
[2025-03-10T15:39:00.074+0000] {standard_task_runner.py:60} INFO - Started process 6437 to run task
[2025-03-10T15:39:00.077+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_xcom', 'upload_to_clickhouse', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/5_1_2_xcom.py', '--cfg-path', '/tmp/tmp0_w1ejs6']
[2025-03-10T15:39:00.078+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask upload_to_clickhouse
[2025-03-10T15:39:00.111+0000] {task_command.py:423} INFO - Running <TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T15:39:00.153+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_xcom' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-10T15:39:00.266+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/5_1_2_xcom.py", line 62, in upload_to_clickhouse
    for file in files:
TypeError: 'NoneType' object is not iterable
[2025-03-10T15:39:00.271+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_xcom, task_id=upload_to_clickhouse, execution_date=20240101T000000, start_date=20250310T153900, end_date=20250310T153900
[2025-03-10T15:39:00.281+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task upload_to_clickhouse ('NoneType' object is not iterable; 6437)
[2025-03-10T15:39:00.290+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-10T15:39:00.300+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T15:43:11.540+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T15:43:11.547+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T15:43:11.547+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T15:43:11.559+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-01 00:00:00+00:00
[2025-03-10T15:43:11.564+0000] {standard_task_runner.py:60} INFO - Started process 6661 to run task
[2025-03-10T15:43:11.567+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_xcom', 'upload_to_clickhouse', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/5_1_2_xcom.py', '--cfg-path', '/tmp/tmp4l86r9o8']
[2025-03-10T15:43:11.569+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask upload_to_clickhouse
[2025-03-10T15:43:11.599+0000] {task_command.py:423} INFO - Running <TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T15:43:11.645+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_xcom' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-10T15:43:11.875+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-03-10T15:43:12.136+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T15:43:12.140+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_xcom, task_id=upload_to_clickhouse, execution_date=20240101T000000, start_date=20250310T154311, end_date=20250310T154312
[2025-03-10T15:43:12.181+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T15:43:12.191+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
