[2025-03-10T15:39:08.128+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-10T15:39:08.135+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-10T15:39:08.136+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T15:39:08.147+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-02 00:00:00+00:00
[2025-03-10T15:39:08.154+0000] {standard_task_runner.py:60} INFO - Started process 6475 to run task
[2025-03-10T15:39:08.156+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_xcom', 'upload_to_clickhouse', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/5_1_2_xcom.py', '--cfg-path', '/tmp/tmp5w23o7k1']
[2025-03-10T15:39:08.159+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask upload_to_clickhouse
[2025-03-10T15:39:08.195+0000] {task_command.py:423} INFO - Running <TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-02T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T15:39:08.251+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_xcom' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2025-03-10T15:39:08.264+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/5_1_2_xcom.py", line 62, in upload_to_clickhouse
    for file in files:
TypeError: 'int' object is not iterable
[2025-03-10T15:39:08.276+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_xcom, task_id=upload_to_clickhouse, execution_date=20240102T000000, start_date=20250310T153908, end_date=20250310T153908
[2025-03-10T15:39:08.289+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task upload_to_clickhouse ('int' object is not iterable; 6475)
[2025-03-10T15:39:08.330+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-10T15:39:08.349+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T15:43:19.499+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-10T15:43:19.506+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-10T15:43:19.506+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T15:43:19.521+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-02 00:00:00+00:00
[2025-03-10T15:43:19.526+0000] {standard_task_runner.py:60} INFO - Started process 6699 to run task
[2025-03-10T15:43:19.529+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_xcom', 'upload_to_clickhouse', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/5_1_2_xcom.py', '--cfg-path', '/tmp/tmp92olev87']
[2025-03-10T15:43:19.531+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask upload_to_clickhouse
[2025-03-10T15:43:19.563+0000] {task_command.py:423} INFO - Running <TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-02T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T15:43:19.622+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_xcom' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2025-03-10T15:43:19.772+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-03-10T15:43:20.276+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T15:43:20.282+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_xcom, task_id=upload_to_clickhouse, execution_date=20240102T000000, start_date=20250310T154319, end_date=20250310T154320
[2025-03-10T15:43:20.304+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T15:43:20.314+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
