[2025-03-03T14:15:27.146+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:15:27.153+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:15:27.153+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:15:27.167+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-04 00:00:00+00:00
[2025-03-03T14:15:27.173+0000] {standard_task_runner.py:60} INFO - Started process 1723 to run task
[2025-03-03T14:15:27.175+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpi6f7fm01']
[2025-03-03T14:15:27.177+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask transform_data
[2025-03-03T14:15:27.206+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:15:27.250+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2025-03-03T14:15:27.252+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:15:27.256+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240104T000000, start_date=20250303T141527, end_date=20250303T141527
[2025-03-03T14:15:27.269+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task transform_data (not well-formed (invalid token): line 1, column 0; 1723)
[2025-03-03T14:15:27.308+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:18:12.184+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:18:12.191+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:18:12.191+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:18:12.206+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-04 00:00:00+00:00
[2025-03-03T14:18:12.213+0000] {standard_task_runner.py:60} INFO - Started process 1943 to run task
[2025-03-03T14:18:12.217+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpc1b6oha0']
[2025-03-03T14:18:12.218+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask transform_data
[2025-03-03T14:18:12.253+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:18:12.302+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2025-03-03T14:18:12.303+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:18:12.308+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240104T000000, start_date=20250303T141812, end_date=20250303T141812
[2025-03-03T14:18:12.318+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task transform_data (not well-formed (invalid token): line 1, column 0; 1943)
[2025-03-03T14:18:12.349+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:25:03.229+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:25:03.237+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:25:03.238+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:25:03.251+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-04 00:00:00+00:00
[2025-03-03T14:25:03.258+0000] {standard_task_runner.py:60} INFO - Started process 2268 to run task
[2025-03-03T14:25:03.268+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpmxe84ea8']
[2025-03-03T14:25:03.271+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask transform_data
[2025-03-03T14:25:03.309+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:25:03.386+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2025-03-03T14:25:03.396+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:25:03.402+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240104T000000, start_date=20250303T142503, end_date=20250303T142503
[2025-03-03T14:25:03.441+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T14:27:51.161+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:27:51.166+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-03T14:27:51.167+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:27:51.180+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-04 00:00:00+00:00
[2025-03-03T14:27:51.186+0000] {standard_task_runner.py:60} INFO - Started process 2575 to run task
[2025-03-03T14:27:51.188+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmp3z9zqvnn']
[2025-03-03T14:27:51.189+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask transform_data
[2025-03-03T14:27:51.216+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:27:51.259+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2025-03-03T14:27:51.271+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:27:51.274+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240104T000000, start_date=20250303T142751, end_date=20250303T142751
[2025-03-03T14:27:51.321+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T09:48:54.595+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-10T09:48:54.601+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-03-10T09:48:54.601+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T09:48:54.613+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-04 00:00:00+00:00
[2025-03-10T09:48:54.618+0000] {standard_task_runner.py:60} INFO - Started process 375 to run task
[2025-03-10T09:48:54.621+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpard_008p']
[2025-03-10T09:48:54.623+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask transform_data
[2025-03-10T09:48:54.651+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-04T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T09:48:54.704+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2025-03-10T09:48:54.710+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T09:48:54.715+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240104T000000, start_date=20250310T094854, end_date=20250310T094854
[2025-03-10T09:48:54.754+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
