[2025-03-03T14:15:16.581+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:15:16.587+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:15:16.587+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:15:16.597+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-03 00:00:00+00:00
[2025-03-03T14:15:16.601+0000] {standard_task_runner.py:60} INFO - Started process 1687 to run task
[2025-03-03T14:15:16.604+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpgvhiyn_f']
[2025-03-03T14:15:16.605+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask transform_data
[2025-03-03T14:15:16.631+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:15:16.670+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2025-03-03T14:15:16.671+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:15:16.676+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240103T000000, start_date=20250303T141516, end_date=20250303T141516
[2025-03-03T14:15:16.684+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task transform_data (not well-formed (invalid token): line 1, column 0; 1687)
[2025-03-03T14:15:16.696+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:18:02.230+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:18:02.235+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:18:02.236+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:18:02.248+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-03 00:00:00+00:00
[2025-03-03T14:18:02.252+0000] {standard_task_runner.py:60} INFO - Started process 1904 to run task
[2025-03-03T14:18:02.255+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpjq4x4yvk']
[2025-03-03T14:18:02.256+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask transform_data
[2025-03-03T14:18:03.050+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:18:03.095+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2025-03-03T14:18:03.096+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:18:03.101+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240103T000000, start_date=20250303T141802, end_date=20250303T141803
[2025-03-03T14:18:03.115+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task transform_data (not well-formed (invalid token): line 1, column 0; 1904)
[2025-03-03T14:18:03.153+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:24:49.302+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:24:49.308+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:24:49.309+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:24:49.319+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-03 00:00:00+00:00
[2025-03-03T14:24:49.326+0000] {standard_task_runner.py:60} INFO - Started process 2211 to run task
[2025-03-03T14:24:49.329+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmp3tftawl3']
[2025-03-03T14:24:49.331+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask transform_data
[2025-03-03T14:24:49.364+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:24:49.410+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2025-03-03T14:24:49.418+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:24:49.421+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240103T000000, start_date=20250303T142449, end_date=20250303T142449
[2025-03-03T14:24:49.461+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T14:27:38.076+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:27:38.081+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-03T14:27:38.081+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:27:38.091+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-03 00:00:00+00:00
[2025-03-03T14:27:38.096+0000] {standard_task_runner.py:60} INFO - Started process 2517 to run task
[2025-03-03T14:27:38.098+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpfi1njyjw']
[2025-03-03T14:27:38.099+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask transform_data
[2025-03-03T14:27:38.123+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:27:38.165+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2025-03-03T14:27:38.177+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:27:38.180+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240103T000000, start_date=20250303T142738, end_date=20250303T142738
[2025-03-03T14:27:38.231+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T09:48:41.248+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-10T09:48:41.258+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-10T09:48:41.258+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T09:48:41.270+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-03 00:00:00+00:00
[2025-03-10T09:48:41.276+0000] {standard_task_runner.py:60} INFO - Started process 319 to run task
[2025-03-10T09:48:41.279+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpvp5jxoyr']
[2025-03-10T09:48:41.281+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask transform_data
[2025-03-10T09:48:41.337+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-03T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T09:48:41.447+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2025-03-10T09:48:41.460+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T09:48:41.469+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240103T000000, start_date=20250310T094841, end_date=20250310T094841
[2025-03-10T09:48:41.533+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
