[2025-02-27T09:48:20.864+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-03T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
