[2025-03-12T14:39:44.185+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-12T14:39:44.192+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-12T14:39:44.193+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:39:44.210+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-12T14:39:44.217+0000] {standard_task_runner.py:60} INFO - Started process 1651 to run task
[2025-03-12T14:39:44.220+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmpj9n3dg6j']
[2025-03-12T14:39:44.222+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask transform_data
[2025-03-12T14:39:44.256+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:39:44.312+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-12T14:39:44.313+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/5_2_2_house_assignment.py", line 50, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-12T14:39:44.319+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250312T143944, end_date=20250312T143944
[2025-03-12T14:39:44.323+0000] {base.py:83} INFO - Using connection ID 'telegram_id' for task execution.
[2025-03-12T14:39:44.325+0000] {base.py:83} INFO - Using connection ID 'telegram_id' for task execution.
[2025-03-12T14:39:45.123+0000] {_client.py:1740} INFO - HTTP Request: POST https://api.telegram.org/bot7637994734:AAGvM2WRHeVQYm8VJwtx1lyk6bN6LERhzT0/sendMessage "HTTP/1.1 200 OK"
[2025-03-12T14:39:45.137+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task transform_data (not well-formed (invalid token): line 1, column 0; 1651)
[2025-03-12T14:39:45.196+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-12T14:50:34.582+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-12T14:50:34.588+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-12T14:50:34.588+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:50:34.600+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-12T14:50:34.606+0000] {standard_task_runner.py:60} INFO - Started process 2466 to run task
[2025-03-12T14:50:34.609+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmpe6481s52']
[2025-03-12T14:50:34.611+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask transform_data
[2025-03-12T14:50:34.639+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:50:34.688+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-12T14:50:34.703+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-12T14:50:34.706+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250312T145034, end_date=20250312T145034
[2025-03-12T14:50:34.741+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-12T14:52:33.768+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-12T14:52:33.774+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-12T14:52:33.774+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:52:33.787+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-12T14:52:33.794+0000] {standard_task_runner.py:60} INFO - Started process 2811 to run task
[2025-03-12T14:52:33.797+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmp3_shz_mx']
[2025-03-12T14:52:33.799+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask transform_data
[2025-03-12T14:52:33.835+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:52:33.897+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-12T14:52:33.912+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-12T14:52:33.916+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250312T145233, end_date=20250312T145233
[2025-03-12T14:52:33.970+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
