[2025-02-27T10:28:07.198+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2025-02-27T10:28:07.203+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2025-02-27T10:28:07.204+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-27T10:28:07.215+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse_task> on 2024-01-11 00:00:00+00:00
[2025-02-27T10:28:07.220+0000] {standard_task_runner.py:60} INFO - Started process 6103 to run task
[2025-02-27T10:28:07.223+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '3_4_2_homework_assignment', 'upload_to_clickhouse_task', 'scheduled__2024-01-11T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/3_4_2_homework_assignment.py', '--cfg-path', '/tmp/tmpoi3_4r09']
[2025-02-27T10:28:07.224+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask upload_to_clickhouse_task
[2025-02-27T10:28:07.250+0000] {task_command.py:423} INFO - Running <TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [running]> on host ea5964584459
[2025-02-27T10:28:07.292+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='3_4_2_homework_assignment' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-11T00:00:00+00:00'
[2025-02-27T10:28:07.303+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/3_4_2_homework_assignment.py", line 92, in upload_to_clickhouse
    client.execute(f'INSERT INTO {table_name} VALUES', data_frame.to_dict('records'))
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 376, in execute
    rv = self.process_insert_query(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 607, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 658, in send_data
    block = block_cls(sample_block.columns_with_types, chunk,
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 40, in __init__
    self.data = self.normalize(data or [])
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 128, in normalize
    self._mutate_dicts_to_rows(data)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 159, in _mutate_dicts_to_rows
    return self._pure_mutate_dicts_to_rows(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 186, in _pure_mutate_dicts_to_rows
    new_data.append(row[name])
KeyError: 'source'
[2025-02-27T10:28:07.309+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=3_4_2_homework_assignment, task_id=upload_to_clickhouse_task, execution_date=20240111T000000, start_date=20250227T102807, end_date=20250227T102807
[2025-02-27T10:28:07.317+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task upload_to_clickhouse_task ('source'; 6103)
[2025-02-27T10:28:07.356+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-27T10:28:07.364+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T10:36:29.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2025-02-27T10:36:29.260+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2025-02-27T10:36:29.260+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-27T10:36:29.278+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse_task> on 2024-01-11 00:00:00+00:00
[2025-02-27T10:36:29.284+0000] {standard_task_runner.py:60} INFO - Started process 6763 to run task
[2025-02-27T10:36:29.286+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '3_4_2_homework_assignment', 'upload_to_clickhouse_task', 'scheduled__2024-01-11T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/3_4_2_homework_assignment.py', '--cfg-path', '/tmp/tmpwsfl7ynq']
[2025-02-27T10:36:29.288+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask upload_to_clickhouse_task
[2025-02-27T10:36:29.318+0000] {task_command.py:423} INFO - Running <TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [running]> on host ea5964584459
[2025-02-27T10:36:29.365+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='3_4_2_homework_assignment' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-11T00:00:00+00:00'
[2025-02-27T10:36:29.379+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/3_4_2_homework_assignment.py", line 93, in upload_to_clickhouse
    client.execute(f'INSERT INTO {table_name} VALUES', data_frame.to_dict('records'))
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 376, in execute
    rv = self.process_insert_query(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 607, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/client.py", line 658, in send_data
    block = block_cls(sample_block.columns_with_types, chunk,
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 40, in __init__
    self.data = self.normalize(data or [])
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 128, in normalize
    self._mutate_dicts_to_rows(data)
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 159, in _mutate_dicts_to_rows
    return self._pure_mutate_dicts_to_rows(
  File "/home/airflow/.local/lib/python3.9/site-packages/clickhouse_driver/block.py", line 186, in _pure_mutate_dicts_to_rows
    new_data.append(row[name])
KeyError: 'source'
[2025-02-27T10:36:29.386+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=3_4_2_homework_assignment, task_id=upload_to_clickhouse_task, execution_date=20240111T000000, start_date=20250227T103629, end_date=20250227T103629
[2025-02-27T10:36:29.396+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task upload_to_clickhouse_task ('source'; 6763)
[2025-02-27T10:36:29.420+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-27T10:36:29.431+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T10:46:21.646+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2025-02-27T10:46:21.652+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2025-02-27T10:46:21.652+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-27T10:46:21.663+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse_task> on 2024-01-11 00:00:00+00:00
[2025-02-27T10:46:21.667+0000] {standard_task_runner.py:60} INFO - Started process 7448 to run task
[2025-02-27T10:46:21.669+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '3_4_2_homework_assignment', 'upload_to_clickhouse_task', 'scheduled__2024-01-11T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/3_4_2_homework_assignment.py', '--cfg-path', '/tmp/tmpvs76qc5k']
[2025-02-27T10:46:21.670+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask upload_to_clickhouse_task
[2025-02-27T10:46:21.694+0000] {task_command.py:423} INFO - Running <TaskInstance: 3_4_2_homework_assignment.upload_to_clickhouse_task scheduled__2024-01-11T00:00:00+00:00 [running]> on host ea5964584459
[2025-02-27T10:46:21.735+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='3_4_2_homework_assignment' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-11T00:00:00+00:00'
[2025-02-27T10:46:21.748+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-02-27T10:46:21.751+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-27T10:46:21.755+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=3_4_2_homework_assignment, task_id=upload_to_clickhouse_task, execution_date=20240111T000000, start_date=20250227T104621, end_date=20250227T104621
[2025-02-27T10:46:21.803+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-27T10:46:21.812+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
