[2025-03-03T14:14:47.916+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:14:47.923+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:14:47.924+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:14:47.935+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-03T14:14:47.941+0000] {standard_task_runner.py:60} INFO - Started process 1608 to run task
[2025-03-03T14:14:47.944+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmplzgg1p1q']
[2025-03-03T14:14:47.945+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask transform_data
[2025-03-03T14:14:47.975+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:14:48.031+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-03T14:14:48.033+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:14:48.041+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250303T141447, end_date=20250303T141448
[2025-03-03T14:14:48.053+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task transform_data (not well-formed (invalid token): line 1, column 0; 1608)
[2025-03-03T14:14:48.076+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:17:13.859+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:17:13.866+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:17:13.867+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:17:13.880+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-03T14:17:13.885+0000] {standard_task_runner.py:60} INFO - Started process 1821 to run task
[2025-03-03T14:17:13.888+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpr94bqf7s']
[2025-03-03T14:17:13.889+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask transform_data
[2025-03-03T14:17:13.917+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:17:13.957+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-03T14:17:13.958+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:17:13.963+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250303T141713, end_date=20250303T141713
[2025-03-03T14:17:13.973+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task transform_data (not well-formed (invalid token): line 1, column 0; 1821)
[2025-03-03T14:17:13.981+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:24:21.771+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:24:21.776+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:24:21.777+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:24:21.787+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-03T14:24:21.792+0000] {standard_task_runner.py:60} INFO - Started process 2096 to run task
[2025-03-03T14:24:21.794+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmp9qfseu8g']
[2025-03-03T14:24:21.796+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask transform_data
[2025-03-03T14:24:21.823+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:24:21.865+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-03T14:24:21.879+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:24:21.883+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250303T142421, end_date=20250303T142421
[2025-03-03T14:24:21.927+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T14:26:42.423+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:26:42.429+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-03T14:26:42.430+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:26:42.440+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-03T14:26:42.445+0000] {standard_task_runner.py:60} INFO - Started process 2397 to run task
[2025-03-03T14:26:42.447+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpb6pgfilu']
[2025-03-03T14:26:42.449+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask transform_data
[2025-03-03T14:26:42.476+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:26:42.526+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-03T14:26:42.539+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:26:42.543+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250303T142642, end_date=20250303T142642
[2025-03-03T14:26:42.580+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T09:47:47.214+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T09:47:47.221+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-03-10T09:47:47.222+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T09:47:47.232+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-01 00:00:00+00:00
[2025-03-10T09:47:47.238+0000] {standard_task_runner.py:60} INFO - Started process 197 to run task
[2025-03-10T09:47:47.240+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpfze38dli']
[2025-03-10T09:47:47.242+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask transform_data
[2025-03-10T09:47:47.269+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-01T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T09:47:47.315+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-03-10T09:47:47.330+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T09:47:47.334+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240101T000000, start_date=20250310T094747, end_date=20250310T094747
[2025-03-10T09:47:47.373+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
