[2025-03-12T14:40:05.430+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-12T14:40:05.438+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-12T14:40:05.438+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:40:05.491+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-02 00:00:00+00:00
[2025-03-12T14:40:05.501+0000] {standard_task_runner.py:60} INFO - Started process 1699 to run task
[2025-03-12T14:40:05.507+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmp6t5_nhy7']
[2025-03-12T14:40:05.510+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask transform_data
[2025-03-12T14:40:05.556+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:40:05.616+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2025-03-12T14:40:05.617+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/5_2_2_house_assignment.py", line 50, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-12T14:40:05.625+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240102T000000, start_date=20250312T144005, end_date=20250312T144005
[2025-03-12T14:40:05.630+0000] {base.py:83} INFO - Using connection ID 'telegram_id' for task execution.
[2025-03-12T14:40:05.633+0000] {base.py:83} INFO - Using connection ID 'telegram_id' for task execution.
[2025-03-12T14:40:06.470+0000] {_client.py:1740} INFO - HTTP Request: POST https://api.telegram.org/bot7637994734:AAGvM2WRHeVQYm8VJwtx1lyk6bN6LERhzT0/sendMessage "HTTP/1.1 200 OK"
[2025-03-12T14:40:06.487+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task transform_data (not well-formed (invalid token): line 1, column 0; 1699)
[2025-03-12T14:40:06.523+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-12T14:51:38.852+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-12T14:51:38.858+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-12T14:51:38.858+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:51:38.870+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-02 00:00:00+00:00
[2025-03-12T14:51:38.875+0000] {standard_task_runner.py:60} INFO - Started process 2683 to run task
[2025-03-12T14:51:38.878+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmpoiysle5h']
[2025-03-12T14:51:38.880+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask transform_data
[2025-03-12T14:51:38.909+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:51:38.978+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2025-03-12T14:51:38.994+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-12T14:51:39.000+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240102T000000, start_date=20250312T145138, end_date=20250312T145139
[2025-03-12T14:51:39.051+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-12T14:53:15.272+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-12T14:53:15.280+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-12T14:53:15.281+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-12T14:53:15.301+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-02 00:00:00+00:00
[2025-03-12T14:53:15.307+0000] {standard_task_runner.py:60} INFO - Started process 2904 to run task
[2025-03-12T14:53:15.310+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '5_2_2_house_assignment', 'transform_data', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/5_2_2_house_assignment.py', '--cfg-path', '/tmp/tmp6kr5erwe']
[2025-03-12T14:53:15.312+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask transform_data
[2025-03-12T14:53:15.347+0000] {task_command.py:423} INFO - Running <TaskInstance: 5_2_2_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-12T14:53:15.406+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='5_2_2_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2025-03-12T14:53:15.421+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-12T14:53:15.427+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=5_2_2_house_assignment, task_id=transform_data, execution_date=20240102T000000, start_date=20250312T145315, end_date=20250312T145315
[2025-03-12T14:53:15.483+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
