[2025-03-10T15:39:11.606+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-10T15:39:11.613+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-10T15:39:11.614+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T15:39:11.628+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-03 00:00:00+00:00
[2025-03-10T15:39:11.635+0000] {standard_task_runner.py:60} INFO - Started process 6494 to run task
[2025-03-10T15:39:11.637+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_xcom', 'upload_to_clickhouse', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/5_1_2_xcom.py', '--cfg-path', '/tmp/tmpipm88rrj']
[2025-03-10T15:39:11.639+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask upload_to_clickhouse
[2025-03-10T15:39:11.673+0000] {task_command.py:423} INFO - Running <TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-03T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T15:39:11.721+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_xcom' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2025-03-10T15:39:11.732+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/5_1_2_xcom.py", line 62, in upload_to_clickhouse
    for file in files:
TypeError: 'int' object is not iterable
[2025-03-10T15:39:11.738+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_xcom, task_id=upload_to_clickhouse, execution_date=20240103T000000, start_date=20250310T153911, end_date=20250310T153911
[2025-03-10T15:39:11.750+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task upload_to_clickhouse ('int' object is not iterable; 6494)
[2025-03-10T15:39:11.770+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-10T15:39:11.780+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T15:43:23.607+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-10T15:43:23.612+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2025-03-10T15:43:23.613+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T15:43:23.623+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_clickhouse> on 2024-01-03 00:00:00+00:00
[2025-03-10T15:43:23.629+0000] {standard_task_runner.py:60} INFO - Started process 6718 to run task
[2025-03-10T15:43:23.631+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_xcom', 'upload_to_clickhouse', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/5_1_2_xcom.py', '--cfg-path', '/tmp/tmp7a_pms8z']
[2025-03-10T15:43:23.633+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask upload_to_clickhouse
[2025-03-10T15:43:23.662+0000] {task_command.py:423} INFO - Running <TaskInstance: test_xcom.upload_to_clickhouse scheduled__2024-01-03T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T15:43:23.723+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_xcom' AIRFLOW_CTX_TASK_ID='upload_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2025-03-10T15:43:23.867+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-03-10T15:43:24.776+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T15:43:24.781+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_xcom, task_id=upload_to_clickhouse, execution_date=20240103T000000, start_date=20250310T154323, end_date=20250310T154324
[2025-03-10T15:43:24.824+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T15:43:24.833+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
