[2025-03-13T12:57:26.801+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-13T12:57:26.810+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-03-13T12:57:26.810+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-13T12:57:26.824+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-02 00:00:00+00:00
[2025-03-13T12:57:26.834+0000] {standard_task_runner.py:60} INFO - Started process 11407 to run task
[2025-03-13T12:57:26.836+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '6_house_assignment', 'transform_data', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/6_house_assignment.py', '--cfg-path', '/tmp/tmpknln50ws']
[2025-03-13T12:57:26.838+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask transform_data
[2025-03-13T12:57:26.874+0000] {task_command.py:423} INFO - Running <TaskInstance: 6_house_assignment.transform_data scheduled__2024-01-02T00:00:00+00:00 [running]> on host 13d00b3af9e0
[2025-03-13T12:57:26.933+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='6_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2025-03-13T12:57:26.942+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-13T12:57:26.946+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=6_house_assignment, task_id=transform_data, execution_date=20240102T000000, start_date=20250313T125726, end_date=20250313T125726
[2025-03-13T12:57:27.009+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-13T12:57:27.025+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
