[2025-03-03T14:15:38.124+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:15:38.130+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:15:38.130+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:15:38.139+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-05 00:00:00+00:00
[2025-03-03T14:15:38.144+0000] {standard_task_runner.py:60} INFO - Started process 1764 to run task
[2025-03-03T14:15:38.147+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpdnr9cq67']
[2025-03-03T14:15:38.148+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask transform_data
[2025-03-03T14:15:38.174+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:15:38.214+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-03T14:15:38.215+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:15:38.220+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240105T000000, start_date=20250303T141538, end_date=20250303T141538
[2025-03-03T14:15:38.229+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task transform_data (not well-formed (invalid token): line 1, column 0; 1764)
[2025-03-03T14:15:38.239+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:18:21.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:18:21.284+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:18:21.285+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:18:21.300+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-05 00:00:00+00:00
[2025-03-03T14:18:21.307+0000] {standard_task_runner.py:60} INFO - Started process 1981 to run task
[2025-03-03T14:18:21.310+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpr8ox53w_']
[2025-03-03T14:18:21.320+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask transform_data
[2025-03-03T14:18:21.355+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:18:21.408+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-03T14:18:21.409+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_4_house_assignment.py", line 47, in transform_data
    tree = ET.parse(s_file, parser=parser).getroot()
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 586, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
[2025-03-03T14:18:21.415+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240105T000000, start_date=20250303T141821, end_date=20250303T141821
[2025-03-03T14:18:21.425+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task transform_data (not well-formed (invalid token): line 1, column 0; 1981)
[2025-03-03T14:18:21.453+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-03T14:25:17.143+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:25:17.148+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:25:17.149+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:25:17.158+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-05 00:00:00+00:00
[2025-03-03T14:25:17.163+0000] {standard_task_runner.py:60} INFO - Started process 2326 to run task
[2025-03-03T14:25:17.165+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpcpg8g47v']
[2025-03-03T14:25:17.167+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask transform_data
[2025-03-03T14:25:17.197+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:25:17.246+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-03T14:25:17.256+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:25:17.261+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240105T000000, start_date=20250303T142517, end_date=20250303T142517
[2025-03-03T14:25:17.298+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T14:28:07.791+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:28:07.797+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-03T14:28:07.797+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T14:28:07.808+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-05 00:00:00+00:00
[2025-03-03T14:28:07.813+0000] {standard_task_runner.py:60} INFO - Started process 2632 to run task
[2025-03-03T14:28:07.815+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmpfzjjfr51']
[2025-03-03T14:28:07.817+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask transform_data
[2025-03-03T14:28:07.841+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-03T14:28:07.889+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-03T14:28:07.904+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-03T14:28:07.908+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240105T000000, start_date=20250303T142807, end_date=20250303T142807
[2025-03-03T14:28:07.948+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-10T09:49:08.100+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-10T09:49:08.105+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2025-03-10T09:49:08.105+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-10T09:49:08.115+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data> on 2024-01-05 00:00:00+00:00
[2025-03-10T09:49:08.120+0000] {standard_task_runner.py:60} INFO - Started process 434 to run task
[2025-03-10T09:49:08.122+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '4_4_house_assignment', 'transform_data', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/4_4_house_assignment.py', '--cfg-path', '/tmp/tmppghvgi49']
[2025-03-10T09:49:08.124+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask transform_data
[2025-03-10T09:49:08.148+0000] {task_command.py:423} INFO - Running <TaskInstance: 4_4_house_assignment.transform_data scheduled__2024-01-05T00:00:00+00:00 [running]> on host 9a2e4036dec3
[2025-03-10T09:49:08.195+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_4_house_assignment' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2025-03-10T09:49:08.202+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-10T09:49:08.206+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=4_4_house_assignment, task_id=transform_data, execution_date=20240105T000000, start_date=20250310T094908, end_date=20250310T094908
[2025-03-10T09:49:08.255+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
